# Generated by Django 5.2.7 on 2025-11-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Welcome To T-CONSULTANCY', max_length=200)),
                ('subtitle', models.CharField(default='Diam dolor diam ipsum sit. Clita erat ipsum et lorem stet no lorem sit clita duo justo magna dolore', max_length=300)),
                ('description', models.TextField(default='Et stet ipsum nonumy rebum eos justo, accusam invidunt aliquyam stet magna at et sanctus, vero sea sit amet dolores, sit dolor duo invidunt dolor, kasd rebum consetetur diam invidunt erat stet.')),
                ('quote_button_text', models.CharField(default='Get A Quote', max_length=50)),
                ('service_1_title', models.CharField(default='Business Planning', max_length=100)),
                ('service_1_description', models.TextField(default='Tempor erat elitr rebum at clita. Diam dolor ipsum amet eos erat ipsum lorem et sit sed stet lorem sit clita duo')),
                ('service_1_icon', models.CharField(default='fa-user-tie', max_length=50)),
                ('service_2_title', models.CharField(default='Financial Analysis', max_length=100)),
                ('service_2_description', models.TextField(default='Tempor erat elitr rebum at clita. Diam dolor ipsum amet eos erat ipsum lorem et sit sed stet lorem sit clita duo')),
                ('service_2_icon', models.CharField(default='fa-chart-line', max_length=50)),
                ('service_3_title', models.CharField(default='Legal Advisory', max_length=100)),
                ('service_3_description', models.TextField(default='Tempor erat elitr rebum at clita. Diam dolor ipsum amet eos erat ipsum lorem et sit sed stet lorem sit clita duo')),
                ('service_3_icon', models.CharField(default='fa-balance-scale', max_length=50)),
            ],
        ),
    ]
