# Generated by Django 5.2.7 on 2025-11-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stayupdate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stayupdate',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
