# Generated by Django 5.2.7 on 2025-12-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxAdvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('income_tax', 'Income Tax'), ('gst', 'GST'), ('investment', 'Investment & Savings'), ('business_tax', 'Business Tax')], max_length=50)),
                ('short_tip', models.CharField(max_length=255)),
                ('detailed_advice', models.TextField()),
                ('country', models.CharField(default='India', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tax Advice',
                'verbose_name_plural': 'Tax Advice',
                'ordering': ['-created_at'],
            },
        ),
    ]
