# Generated by Django 5.2.7 on 2025-10-31 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=150)),
                ('profession', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('client_image', models.ImageField(upload_to='testimonials/')),
            ],
        ),
    ]
