# Generated by Django 5.2.7 on 2025-10-25 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='ContactMessage',
        ),
    ]
