# Generated by Django 5.2.7 on 2025-10-25 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_rename_contact_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
