# Generated by Django 5.2.7 on 2025-10-31 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_desc',
            field=models.TextField(default='default service description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='service_title',
            field=models.CharField(default='default service title', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='service_read_link',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
