# Generated by Django 5.2.7 on 2025-10-31 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourservice', '0002_service_service_desc_service_service_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_icon',
            field=models.CharField(default='fa-cog', help_text='fa-chart-line', max_length=150),
        ),
    ]
